services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    profiles:
      - with-server
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@timescaledb:5432/postgres
    ports:
      - '3000:3000'

volumes:
  timescaledb_data:
